sudo: false
# 2017/09/03: Stick on precise since FreeType support is missing in PHP 5.5 and 5.6 images
dist: precise
addons:
  apt_packages:
    - language-pack-fr
    - language-pack-fr-base
language: php
cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/casperjs-1.1.3
php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- nightly
matrix:
  allow_failures:
  - php: nightly
  - php: 7.2
env:
- DB_USER=root DB_HOST=127.0.0.1
before_script:
- phpenv config-add travis.php.ini
# xdebug.ini is missing in 7.2 distrib.
# - phpenv config-rm xdebug.ini
- composer self-update
- composer install --no-interaction --prefer-dist
- sh -c "mysql -u$DB_USER -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS
  thelia;SET FOREIGN_KEY_CHECKS = 1;'; fi"
- php Thelia thelia:install --db_host=$DB_HOST --db_username=$DB_USER --db_name=thelia
- php setup/faker.php -r 0
- php Thelia module:refresh
- php Thelia module:activate Colissimo
- php Thelia module:activate Cheque
- php Thelia module:activate HookTest
- php Thelia module:activate VirtualProductDelivery
- php Thelia admin:create --login_name thelia2 --password thelia2 --last_name thelia2 --first_name thelia2 --email thelia2@example.com
- export PHANTOMJS_EXECUTABLE="$(which phantomjs)"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- php -S 127.0.0.1:8000 -t web/ >/dev/null 2>&1 &
- sleep 3
- bash tests/travis/install-casperjs.sh
- export PATH=$PATH:$HOME/casperjs-1.1.3/bin
script: "./run-tests.sh"
notifications:
  slack:
    secure: juEYyXsn7m8tnSQXOBj9MtS0izIs1Y4ISAfEbD6oINnEt56XXgAj3ZbEPJsJIMl/z2ThksqT++0+84f3a/IJ4RYiQUwKNCBjz1vjk544ma3cqn5SETTKKeiaUKKJCM88VmfybJZ/BMuiLMFghsI9U2F1SIa+GSYicYPA2dQ4BX0=
